export const pageInfo = {
  avatar: 'https://scontent.fssa2-1.fna.fbcdn.net/v/t1.0-9/32105083_1461921467240717_2863832073544663040_n.jpg?_nc_cat=0&oh=3c7f14d76ec0017e7025a183c3df36d5&oe=5BD73AD3',
  name: 'Guhan\'s Cowork House',
  description: '<p>Guhan\'s Cowork House é um espaço especializado com projetos voltados para arte e cultura</p><p>Possui espaços pala palestras, reuniões, workshops, aulas e muito mais.</p>',
  followedBy: [ '9', '3', '12' ],
  categories: ['cowork','arte','cultura','louge','palestras'],
  facebook: 'https://www.facebook.com/guhanmandarim/',
  instagram: 'https://www.instagram.com/guhanmandarim/',
  location: {
    address: 'Largo da dinha, Rio Vermelho, Salvador - BA',
    coordinates: { lat: -13.011441, lng: -38.491617 },
  },
  openAt: 'Aberto às terças e quintas, das 14h às 19h',
  photos: [
    {
      author: 'rhuan',
      description: 'Uma lorem picsum',
      thumb: 'https://picsum.photos/200?image=0',
      url: 'https://picsum.photos/600?image=0',
    },
    {
      author: 'rhuan',
      description: 'Uma lorem picsum',
      thumb: 'https://picsum.photos/200?image=1',
      url: 'https://picsum.photos/600?image=1',
    },
    {
      author: 'rhuan',
      description: 'Uma lorem picsum',
      thumb: 'https://picsum.photos/200?image=2',
      url: 'https://picsum.photos/600?image=2',
    },
    {
      author: 'rhuan',
      description: 'Uma lorem picsum',
      thumb: 'https://picsum.photos/200?image=3',
      url: 'https://picsum.photos/600?image=3',
    },
    {
      author: 'rhuan',
      description: 'Uma lorem picsum',
      thumb: 'https://picsum.photos/200?image=4',
      url: 'https://picsum.photos/600?image=4',
    },
    {
      author: 'rhuan',
      description: 'Uma lorem picsum',
      thumb: 'https://picsum.photos/200?image=5',
      url: 'https://picsum.photos/600?image=5',
    },
    {
      author: 'rhuan',
      description: 'Uma lorem picsum',
      thumb: 'https://picsum.photos/200?image=6',
      url: 'https://picsum.photos/600?image=6',
    },
    {
      author: 'rhuan',
      description: 'Uma lorem picsum',
      thumb: 'https://picsum.photos/200?image=7',
      url: 'https://picsum.photos/600?image=7',
    },
    {
      author: 'rhuan',
      description: 'Uma lorem picsum',
      thumb: 'https://picsum.photos/200?image=8',
      url: 'https://picsum.photos/600?image=8',
    },
    {
      author: 'rhuan',
      description: 'Uma lorem picsum',
      thumb: 'https://picsum.photos/200?image=9',
      url: 'https://picsum.photos/600?image=9',
    },
    {
      author: 'rhuan',
      description: 'Uma lorem picsum',
      thumb: 'https://picsum.photos/200?image=10',
      url: 'https://picsum.photos/600?image=10',
    },
    {
      author: 'rhuan',
      description: 'Uma lorem picsum',
      thumb: 'https://picsum.photos/200?image=11',
      url: 'https://picsum.photos/600?image=11',
    },
    {
      author: 'rhuan',
      description: 'Uma lorem picsum',
      thumb: 'https://picsum.photos/200?image=12',
      url: 'https://picsum.photos/600?image=12',
    },
    {
      author: 'rhuan',
      description: 'Uma lorem picsum',
      thumb: 'https://picsum.photos/200?image=13',
      url: 'https://picsum.photos/600?image=13',
    },
    {
      author: 'rhuan',
      description: 'Uma lorem picsum',
      thumb: 'https://picsum.photos/200?image=14',
      url: 'https://picsum.photos/600?image=14',
    },
    {
      author: 'rhuan',
      description: 'Uma lorem picsum',
      thumb: 'https://picsum.photos/200?image=15',
      url: 'https://picsum.photos/600?image=15',
    },
    {
      author: 'rhuan',
      description: 'Uma lorem picsum',
      thumb: 'https://picsum.photos/200?image=16',
      url: 'https://picsum.photos/600?image=16',
    },
    {
      author: 'rhuan',
      description: 'Uma lorem picsum',
      thumb: 'https://picsum.photos/200?image=17',
      url: 'https://picsum.photos/600?image=17',
    },
    {
      author: 'rhuan',
      description: 'Uma lorem picsum',
      thumb: 'https://picsum.photos/200?image=18',
      url: 'https://picsum.photos/600?image=18',
    },
    {
      author: 'rhuan',
      description: 'Uma lorem picsum',
      thumb: 'https://picsum.photos/200?image=19',
      url: 'https://picsum.photos/600?image=19',
    },
  ],
  events: [
    {
      name: 'Eventão do Robyssão',
      location: {
        address: 'Casa do Serjão',
        coordinates: { lat: 14.2, lng: 11 },
      },
      flyer: 'https://picsum.photos/200?image=11',
      start: new Date(),
      end: new Date(),
    },
    {
      name: 'Bailo do Momento na casa do Juca',
      location: {
        address: 'Casa do Casa do Juca',
        coordinates: { lat: 14.2, lng: 11 },
      },
      flyer: 'https://picsum.photos/200?image=31',
      start: new Date(),
      end: new Date(),
    },
    {
      name: 'O que tem pra hoje',
      location: {
        address: 'Na sua casa',
        coordinates: { lat: 14.2, lng: 11 },
      },
      flyer: 'https://picsum.photos/200?image=19',
      start: new Date(),
      end: new Date(),
    },
    {
      name: 'Sétima tabela do quarto andar',
      location: {
        address: 'Quarto andar, sétima tabela',
        coordinates: { lat: 14.2, lng: 11 },
      },
      flyer: 'https://picsum.photos/200?image=111',
      start: new Date(),
      end: new Date(),
    },
  ]
};
